apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: [your_secret_name]
  namespace: default
spec:
  secretName: [your_secret_name]
  issuerRef:
    name: letsencrypt-stage
    kind: Issuer
  commonName: "*.your.domain.example"
  duration: 2160h # 90d
  renewBefore: 720h # 30d before SSL will expire, renew it
  dnsNames:
    - "your.domain.example"
    - "*.your.domain.example"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "" # Control auto-reflection namespaces